language: groovy

jdk:
- oraclejdk7
- oraclejdk8

branches:
  only:
    - master

before_script:
- chmod +x grailsw

script: ./grailsw clean && yes | ./grailsw refresh-dependencies && ./grailsw test-app
